apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democicdk8s 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: agrocd/democicdk8s-manifest
    repoURL: https://github.com/mjkvodoi456/DemoCICDK8s.git
    targetRevision: HEAD
  syncPolicy: {}
